### ISSUE TITLE
Release 5 Issues List

### ISSUE THREAD

**Issue by satterly** [alerta/alerta#401]
Following on from the [FAQ](https://github.com/guardian/alerta/wiki/Release-5-FAQ), this is a list of outstanding issues...
- [x] amqp plugin (eg `get_body()`)
- [x] mailer (uses alertaclient do parse alerts off AMQP topic)
- [x] zabbix (uses alerta client to send alerts)
- [x] update documentation
- [x] fix example code
- [ ] some complex URL queries for Postgres are incomplete
- [x] complete regression testing eg. lots of vagrant boxes
- [ ] "official" docker image does not support Postgres, yet
- [x] alerta CLI `watch` command
- [x] missing .netrc crashes CLI
- [x] `alerta heartbeats --alert` missing
- [x] date timezone issue with amqp plugin
- [x] add a postgres vagrant box

**Comment by satterly** [comment]
Fixed alerta/zabbix-alerta#21

**Comment by xp-1000** [comment]
Hi 
I thought open a new issue when I seen this one.
I try to set up a simple install of alerta server with email alert sending to plug it to my kapacitor.
Thanks to you, alerta-mailer works fine alone but since I updated the alerta server to v5 amqp plugin is not loaded anymore : 

> ERROR in __init__ [/usr/lib/python3.6/site-packages/alerta/plugins/__init__.py:57]:
> Server plugin 'amqp' could not be loaded: 'FakeApp' object has no attribute 'debug'

It seems to be related to this issue scope but I could open a new one on alerta-amqp contrib repo if you prefer.
Thanks

**Comment by satterly** [comment]
@xp-1000 this has already been fixed [here](alerta/alerta-contrib#149). try upgrading the amqp plugin using...
```
$ pip install git+https://github.com/alerta/alerta-contrib.git#subdirectory=plugins/amqp --upgrade
```

**Comment by xp-1000** [comment]
You are right, I forgot to upgrade, sorry for that.

**Comment by satterly** [comment]
@xp-1000 no problem.

**Comment by satterly** [comment]
alerta client `watch` command added. see alerta/python-alerta-client#87

**Comment by sushovan23** [comment]
How the blackout feature work with new release? I can see notify is always True for me.

**Comment by sushovan23** [comment]
I checked & found that blackout plugin wasn't enabled in my config. Is there anything else needed to make blackout work? I do notice the `NOTIFICATION_BLACKOUT` in blackout plugin code but we are not using that variable so alerts are being suppressed by default blackout plugin for me rather than building it in each of the plugins.

**Comment by kaggis** [comment]
Hello, 
After upgrading alerta-components to the lastest 5.x releases the following error appeared to `alerta-mailer` log:
```
WARNING:mailer:dates must be ISO 8601 date format YYYY-MM-DDThh:mm:ss.sssZ
dates must be ISO 8601 date format YYYY-MM-DDThh:mm:ss.sssZ
```

I've managed to replicate the issue by deploying the alerta-components (latest 5.x versions) in a clean environment: 
```
alerta (5.0.7)
alerta-amqp (5.4.0)
alerta-mailer (5.0.2)
alerta-server (5.0.2)
```
Note: alerta-amqp runs with default mongo backend. 
Rolling `alerta-server` back to `4.10` eliminated the issue.

By examining amqp messages in mongo, issue seems to generate in `alerta_amqp` during alert serialization: the datetime objects don't hold any tzinfo which kombu's default json serializer expects to see in order to produce 'Z' datetime strings.

**Comment by satterly** [comment]
Hi @kaggis Thanks for reporting this in such detail and even better, thanks for the fix. After investigating this myself to ensure it wasn't a wider issue I realised that the problem isn't that the dates aren't "timezone aware" it's that the JSON serializer doesn't format the dates correctly. So my preferred fix can be seen at alerta/alerta-contrib#158 as such I've closed yours as it's not required. Thanks again for your contribution.
