### ISSUE TITLE
7.4.6: AttributeError: module 'alerta.build' has no attribute 'BUILD_NUMBER'

### ISSUE THREAD

**Issue by wo250012** [alerta/alerta#1190]
**Issue Summary**

I get AttributeError: module 'alerta.build' has no attribute 'BUILD_NUMBER' when trying to access the about page after upgrading to V7.4.6

**Environment**
- OS:linux
- API version: 7.4.1
- Deployment: self hosted
- For self-hosted, WSGI environment: nginx/uwsgi

- Database: mongodb

- Server config:
  Auth enabled? Yes
  Auth provider? LDAP
  Customer views? No

**To Reproduce**
I did a wget on the 7.4.6 release
unziped/untared
while activated in my virtualenv I ran "python setup.py install"
It seems to install fine, "alerta version" shows 7.4.6
Clicking on the about page in the UI give a 500 with AttributeError: module 'alerta.build' has no attribute 'BUILD_NUMBER'

Full error from log:

2020-04-15 19:26:00,138 alerta.app[31043]: [ERROR] module 'alerta.build' has no attribute 'BUILD_NUMBER' request_id=0669af41-49ae-4780-a27f-5a63c9b5dbfc ip=10.104.14.179
Traceback (most recent call last):
  File "/opt/alerta/lib64/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/alerta/lib64/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/alerta/lib64/python3.6/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/opt/alerta/lib64/python3.6/site-packages/alerta_server-7.4.6-py3.6.egg/alerta/auth/decorators.py", line 89, in wrapped
    return f(*args, **kwargs)
  File "/opt/alerta/lib64/python3.6/site-packages/alerta_server-7.4.6-py3.6.egg/alerta/management/views.py", line 61, in manifest
    'build': build.BUILD_NUMBER,
AttributeError: module 'alerta.build' has no attribute 'BUILD_NUMBER'

**Comment by satterly** [comment]
Do not use `python setup.py install`. Use `pip install .` instead. If you use `setup.py` you need to manage and install all the dependencies yourself. Sounds like you missed some. See https://stackoverflow.com/questions/15724093/difference-between-python-setup-py-install-and-pip-install

**Comment by FloSew** [comment]
Sorry to open up this one after it was closed but using Alerta API through docker I got the exact same error.

With docker compose I do:
`  alerta.api:
    image: ghcr.io/alerta/alerta-api:8.7.0
    container_name: alerta.api
    ports:
      - "8080:8080"
    depends_on:
      - alerta.db
    environment:
      - DEBUG=0
      - DATABASE_URL=postgres://postgres:postgres@alerta.db:5432/monitoring
    volumes:
      - ./config/alertad.conf:/app/alertad.conf
    logging:
      options:
        max-file: "3"
        max-size: "50m"
    restart: always`

Then I got the same error:
`alerta.api    | 2023-02-06 22:24:19,130 alerta.app[1]: [ERROR] module 'alerta.build' has no attribute 'BUILD_NUMBER' request_id=2bba7bf4-3a24-4c38-8212-0e767d739aea ip=172.19.0.1
alerta.api    | Traceback (most recent call last):
alerta.api    |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
alerta.api    |     rv = self.dispatch_request()
alerta.api    |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
alerta.api    |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
alerta.api    |   File "/usr/local/lib/python3.8/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
alerta.api    |     resp = make_response(f(*args, **kwargs))
alerta.api    |   File "/usr/local/lib/python3.8/site-packages/alerta/auth/decorators.py", line 129, in wrapped
alerta.api    |     return f(*args, **kwargs)
alerta.api    |   File "/usr/local/lib/python3.8/site-packages/alerta/management/views.py", line 63, in manifest
alerta.api    |     'build': build.BUILD_NUMBER,
alerta.api    | AttributeError: module 'alerta.build' has no attribute 'BUILD_NUMBER'
`

**Comment by FloSew** [comment]
I found the problem. The file alerta/build.py was created empty because setup.py needs git which is not installed in the Dockerfile

```
try:
    with open('alerta/build.py', 'w') as f:
        build = """
        BUILD_NUMBER = '{build_number}'
        BUILD_DATE = '{date}'
        BUILD_VCS_NUMBER = '{revision}'
        """.format(
            build_number=os.environ.get('BUILD_NUMBER', 'PROD'),
            date=datetime.utcnow().strftime('%Y-%m-%dT%H:%M:%SZ'),
            revision=subprocess.check_output(['git', 'rev-parse', 'HEAD']).decode('utf-8').strip()
        ).replace('    ', '')
        f.write(build)`
